model: dino_v2_lora
method: supervised
dataset: flowers102
mode: supervised
num_epochs: 10
batch_size: 64
optimizer: AdamW
lr: 0.0005
momentum: 0.9
weight_decay: 0.05
scheduler: CosineAnnealingLR
warmup_epochs: 0
use_quantization: false
num_classes: 102
lora_rank: 4
