model: mlp_mixer
method: supervised
dataset: cifar10
mode: supervised
num_epochs: 400
batch_size: 128
optimizer: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.1
scheduler: CosineAnnealingLR
warmup_epochs: 0
use_quantization: false
