model: resnet18
method: simsiam
dataset: cifar10
mode: two_crop
num_epochs: 800
batch_size: 512
optimizer: SGD
lr: 0.06
momentum: 0.9
weight_decay: 0.0005
scheduler: CosineAnnealingLR
warmup_epochs: 0
use_quantization: false
