model: timm_lora
backbone_name: vit_base_patch16_224
img_size: 224
method: supervised
dataset: cub200
mode: supervised
num_epochs: 10
batch_size: 64
optimizer: AdamW
lr: 0.0005
momentum: 0.9
weight_decay: 0.05
scheduler: CosineAnnealingLR
warmup_epochs: 0
num_classes: 200
lora_rank: 4
lora_modules: qkv,proj,mlp
qkv_lora_components: q,k,v
