model: timm_pruned_linear_probe
artifact_path: ./pruned/vit_base_flowers102_pretrained_mlp020/pruned_timm_classifier.pth
reset_classifier: true
freeze_encoder: true
method: supervised
dataset: flowers102
mode: supervised
num_epochs: 10
batch_size: 64
optimizer: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.0
scheduler: CosineAnnealingLR
warmup_epochs: 0
num_classes: 102
