source_type: checkpoint
checkpoint_path: ./runs/timm_lora_cifar100_supervised/0507-235431/best_cls_ckpt.pth
output_dir: ./pruned/vit_base_cifar100_mlp020
pruning_ratio: 0.20
pruning_modules: mlp
iterative_steps: 1
global_pruning: false
round_to:
